# Generated by Django 3.1.1 on 2021-02-20 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0005_auto_20210219_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybunch',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='BunchBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('batch_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvests.batchsource')),
                ('bunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvests.bunch')),
            ],
            options={
                'verbose_name': 'Bunch Batch',
                'verbose_name_plural': 'Bunches Batch',
            },
        ),
    ]
